name: PyPI build

on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload wheels to PyPI? (0: no, 1: yes)'
        required: true
        default: '0'

env:
  CIBW_BUILD: cp37-* # FIXME: Enable all versions later to 3.7, and pypy
  CIBW_SKIP: "*-musllinux*"
  CIBW_ARCHS_WINDOWS: auto64
  CIBW_ARCHS_LINUX: auto64
  CIBW_ARCHS_MACOS: x86_64 arm64
  CIBW_BUILD_VERBOSITY: 1

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
            #token: ${{ secrets.ENOKI_JIT_TOKEN }}

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.7'

      - name: Prepare compiler environment for Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v2
        with:
          arch: x64

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.6.1

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  #upload_pypi:
  #  name: Build wheels and upload to PyPI
  #  runs-on: ubuntu-latest
  #  if: ${{ github.event.inputs.upload == '1'}}
  #  needs: [build_wheels]

  #  steps:
  #    - uses: actions/download-artifact@v2
  #      with:
  #        name: wheels
  #        path: dist

  #    - uses: pypa/gh-action-pypi-publish@master
  #      with:
  #        user: __token__
  #        password: ${{ secrets.pypi_password }}
